"""delete table

Revision ID: 2bcea009cc8c
Revises: 
Create Date: 2026-01-12 04:43:44.029176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bcea009cc8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('doctor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_name', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_table('hospital_slots',
    sa.Column('hospitalslot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('hospitalslot_id')
    )
    op.create_index('idx_slot_time', 'hospital_slots', ['start_time', 'end_time'], unique=True)
    op.create_table('operating_hours',
    sa.Column('operating_hour_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('break_start_time', sa.Time(), nullable=True),
    sa.Column('break_end_time', sa.Time(), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('operating_hour_id')
    )
    op.create_index('idx_day_of_week', 'operating_hours', ['day_of_week'], unique=True)
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('patient_name', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('treatments',
    sa.Column('treatment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('treatment_name', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('treatment_id')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_code', sa.String(length=6), nullable=True),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('treatment_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointmentstatus'), nullable=True),
    sa.Column('is_first_visit', sa.Boolean(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.treatment_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index('idx_doctor_time', 'appointments', ['doctor_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_appointments_reservation_code'), 'appointments', ['reservation_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_reservation_code'), table_name='appointments')
    op.drop_index('idx_doctor_time', table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('treatments')
    op.drop_table('patients')
    op.drop_index('idx_day_of_week', table_name='operating_hours')
    op.drop_table('operating_hours')
    op.drop_index('idx_slot_time', table_name='hospital_slots')
    op.drop_table('hospital_slots')
    op.drop_table('doctors')
    # ### end Alembic commands ###
