"""change table

Revision ID: 744702c1c887
Revises: c54ff86d9096
Create Date: 2026-01-12 21:59:44.191584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744702c1c887'
down_revision: Union[str, Sequence[str], None] = 'c54ff86d9096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('doctors', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'deleted_at')
    op.drop_column('doctors', 'is_active')
    # ### end Alembic commands ###
