"""add contraint

Revision ID: c54ff86d9096
Revises: 2bcea009cc8c
Create Date: 2026-01-12 16:58:44.959249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54ff86d9096'
down_revision: Union[str, Sequence[str], None] = '2bcea009cc8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_name_phone_uc', 'patients', ['patient_name', 'phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_phone_uc', 'patients', type_='unique')
    # ### end Alembic commands ###
